name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry with PAT
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin


      # 🔹 Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE_NAME .
          echo "Pushing Image $IMAGE_NAME"
          docker push $IMAGE_NAME
